### ISSUE TITLE
Billable Middleware issue durning install APP

### ISSUE THREAD

**Issue by beingak** [Kyon147/laravel-shopify#33] opened 2022-12-29 10:00 UTC
*Billable Middleware issue durning install APP SPA*

@Kyon147 
i do have install the app using the frontend_engine [REACT] and i am using two middleware [verify.shopify','billable] but after install my billable show this error see the below screen shot.
![Untitled](https://user-images.githubusercontent.com/22137199/209934583-0515a113-867d-4b3f-b733-fe1f105ae0a8.png)

And another one screenshot from my plan table. see the below screen shot:
![Untitled](https://user-images.githubusercontent.com/22137199/209934690-13fbc3ab-c72c-4e35-968f-bf912ac62f1f.png)

Before i were use the older version from the package its working fine but Shopify show me outdated error from my app. and after i did upgrade the package its error occur new error i above mentioned you. can you please let me know how can i solve it.below detail is my updated version detail
osiset/laravel-shopify => 17.3
osiset/basic-shopify-api=>9.0.0
 laravel/framework=> ^8.0

**Comment by ZainSohail** [comment] 2022-12-29 10:39
@beingak can you share details of the exact version (i.e. 17.3.x), there were some PR's which were merged in 17.3.3 which broke install, these were fixed in 17.3.4  (Ref: #15)

**Comment by beingak** [comment] 2022-12-29 10:48
The exact version  is "kyon147/laravel-shopify": "^17.3"

**Comment by ZainSohail** [comment] 2022-12-29 10:51
A simple `composer show` command in your laravel root directory should show the actual version.

![image](https://user-images.githubusercontent.com/6643343/209940924-c17410fe-d062-4bd5-975f-b17361a10ea1.png)

**Comment by ZainSohail** [comment] 2022-12-29 10:57
> @ZainSohail The exact version is "kyon147/laravel-shopify": "^17.3"
> 
> ![Untitled](https://user-images.githubusercontent.com/22137199/209941138-f94a92a9-2cb5-40b8-b16d-ead43a6dd325.png) see above screensheet

You're using the correct version. I'm not sure then what could be the issue, might be authentication.

**Comment by beingak** [comment] 2022-12-29 10:59
@ZainSohail 
I am using the the simple route web.php. You can see the below code:
Route::group(['middleware' => ['verify.shopify','billable']], function(){

    Route::get('/', function () { return view('welcome'); })->name('home');
    Route::get('/{path?}', function () { return view('welcome'); });
});

**Comment by Kyon147** [comment] 2022-12-29 11:04
I vaguely remembering seeing something like this before.

This is happening on install right, so when the user hits the `billable` middleware and does not have a valid plan? Have you tried disabling this for now and trying to trigger a custom billing page?

**Comment by beingak** [comment] 2022-12-29 11:14
@Kyon147 
Without billable is working fine. But i want to use it on app install. Is there anyway how can i use it on app install.

**Comment by beingak** [comment] 2022-12-29 11:21
@Kyon147 
If i am using config/shipfy.php inside this below then billable is working fine
'frontend_engine' => env('SHOPIFY_FRONTEND_ENGINE', 'BLADE'),
but when i am change the BLADE to REACT. its not working [billable] middleware.

**Comment by beingak** [comment] 2022-12-29 11:42
@Kyon147 @ZainSohail 
The another issue i am facing on the host is missing after the billable approved. This param is not return the
{{\Request::get('host')}} host. Have you any idea.

or do i will close this trade.

**Comment by ZainSohail** [comment] 2022-12-29 11:56
> @Kyon147 @ZainSohail The another issue i am facing on the host is missing after the billable approved. This param is not return the {{\Request::get('host')}} host. Have you any idea.
> 
> or do i will close this thread.
 
Shopify only provides host parameter in the initial load of the APP, if you are using redirects or links then make sure you pass the host along with the query to keep it persistent. For eg `<a href="{{ URL::tokenRoute('home', ['host' => \Request::get('host') ]) }}" id="redirect"></a>`, this is how I fixed `host` not being loaded in one of my pages.

As far as I know, this is still in the works but @Kyon147 could help further. 

![image](https://user-images.githubusercontent.com/6643343/209947612-80dc19e5-1ac7-4c15-b4bd-671355da5ef6.png)

**Comment by Kyon147** [comment] 2022-12-29 12:09
@beingak - the host should be returned on the billing success as that was one addition I made recently to make sure my own SPA works as intended.

As @ZainSohail has mentioned though, after that initial `host` that is passed, you need to make sure that your SPA keeps a record of it and loads AppBridge again.

Billing takes you out the iframe and back again, so you need to remember to reinit AppBridge with the host param

**Comment by ZainSohail** [comment] 2022-12-29 12:34
> @beingak - the host should be returned on the billing success as that was one addition I made recently to make sure my own SPA works as intended.
> 
> As @ZainSohail has mentioned though, after that initial `host` that is passed, you need to make sure that your SPA keeps a record of it and loads AppBridge again.
> 
> Billing takes you out the iframe and back again, so you need to remember to reinit AppBridge with the host param

@Kyon147 I think he's onto something because after a successful charge, I don't see the host parameter either. It does show up if I refresh the page and iframe loads again, but after successful charge redirect it does not show up. Check [this screencast](https://drive.google.com/file/d/106MGAQkBku07txugLzy22crJCbl_oEnp/view?usp=sharing).

**Comment by beingak** [comment] 2022-12-29 12:47
@ZainSohail @Kyon147 
same problem i am facing. Let me know if do you have any solution  over it

**Comment by beingak** [comment] 2022-12-29 13:05
@Kyon147 @ZainSohail 
*Can you let us know is there possible to use billable middleware with frontend_engine = REACT.
I am using your package guide step by step.*. I did this changes because Shopify reject the app error occur outdated app.  
But after doing upgrade the version i am facing lot of issues.
Migration issue as well. but i did have solve
![Untitled](https://user-images.githubusercontent.com/22137199/209955134-ff876f84-ef0c-412f-beeb-1a8f8a8a1a48.png)
.

**Comment by Kyon147** [comment] 2022-12-29 13:35
@beingak I'll need to investigate it first and come back to you.

I think in my package I did not use the billable middleware because I handled it a bit more manually - so I will need to check and if there is an issue what the solution is.

**Comment by beingak** [comment] 2022-12-29 13:45
> @beingak I'll need to investigate it first and come back to you.
> 
> I think in my package I did not use the billable middleware because I handled it a bit more manually - so I will need to check and if there is an issue what the solution is.

okay @Kyon147 
It will helpful to all the community.
Thanks

**Comment by Kyon147** [comment] 2022-12-29 15:28
Hi @beingak 

I've had a look and can remember now why, you can't use the Billable middleware with SPA mode.

This is because the user is no longer "logged in" anymore as we let you handle the authentication and JWT yourself inside the SPA app.

I'm going to throw an exception in the next release to warn people.

You can still use the billing routes, to send you customers to the charge screens etc, but you just have to deal with the logic around checking is billing exists or not and how you wish to handle it.

Going to close this for now.

**Closed by Kyon147** 2022-12-29 15:28 UTC
Labels: bug, unconfirmed
