### ISSUE TITLE
Embedded app cannot complete OAuth process due to CSP issue

### ISSUE THREAD

**Issue by harshadcmr** [Kyon147/laravel-shopify#112] opened 2023-03-11 08:59 UTC
## Expected Behavior

1. Hit to backend / route and authenticate 

2. Request URL: {app domain}/authenticate/token?shop={shopname}.myshopify.com&target=%2F%3Fembedded%3D1%26host%xxx&host=yyyy

3. Request URL: {appURL}/?embedded=1&host=xxxx&shop={myshopidydomain}&token=yyyy

Getting 302 Status code for redirection as bellow 

> `Location: https://{myshopify domain}/admin/oauth/authorize?client_id=xxxx&scope=read_products,write_products,read_themes,write_themes,read_orders,read_price_rules,write_price_rules,read_discounts,write_discounts&redirect_uri={appURL}/api/onlineFunction&state=none&grant_options[]=per-user
`

up to this we are getting  CSP Headers as bellow.

> Content-Security-Policy: frame-ancestors https://{shopname}.myshopify.com https://admin.shopify.com

4. Request URL: `https://{shopname}.myshopify.com/admin/oauth/authorize?client_id=xxxx&scope=read_products,write_products,read_themes,write_themes,read_orders,read_price_rules,write_price_rules,read_discounts,write_discounts&redirect_uri={appURL}/api/onlineFunction&state=none&grant_options[]=per-user`

on this request we are getting the following CSP headers 

`content-security-policy: default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=authorize&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Foauth&source%5Bsection%5D=admin&source%5Buuid%5D=1dd05528-652f-45b3-af08-67902853cc55`

## Current Behavior

**Browsers shows this error** 

Refused to frame 'https://{shop}.myshopify.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

 
### Context
* Package Version: v17.4
* Laravel Version: v8.0
* PHP Version: v7.4
* Using a toolset (Docker, Laradock, Vagrant, etc.): No

### Failure Logs

![Screenshot 2023-03-11 at 2 25 52 PM](https://user-images.githubusercontent.com/11991930/224475379-f7633c29-8c6c-4b61-bd5e-154c08362761.png)

![Screenshot 2023-03-11 at 2 10 17 PM](https://user-images.githubusercontent.com/11991930/224475266-c0fdb89f-96bf-40ae-97a0-f6087c756436.png)
![Screenshot 2023-03-11 at 2 13 19 PM](https://user-images.githubusercontent.com/11991930/224475268-d2f4c7e2-b17f-454b-8799-c0244ca981ec.png)

**Comment by harshadcmr** [comment] 2023-03-11 09:07
I tried to add CSP headers inside the nginx server block as 
`#add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; frame-src 'self';";`

but after this, I got some errors to whitelist the other package URLs also . it shows like bellow. 

<img width="1440" alt="Screenshot 2023-03-10 at 3 48 42 PM" src="https://user-images.githubusercontent.com/11991930/224475617-a61e9aea-fca1-4db5-97dd-722e54ff4e66.png">

![Screenshot 2023-03-11 at 11 58 43 AM](https://user-images.githubusercontent.com/11991930/224475502-08e5e039-5127-4723-9208-bd5f6dfeeeeb.png)



### Expected outputs ###

1. need to complete the other procedure and get the online token and offline token  and load the app as embaded 


Note : we hosted front-end module in another sub domain and backend app hosted in another subdomain.

**Comment by Kyon147** [comment] 2023-03-11 11:12
@harshadcmr `https://{shopname}.myshopify.com/admin/oauth/authorize` is no longer inside the app but Shopify itself. This is something we have no control over for the CSP headers - you will probably need to speak with Shopify support as this does not look like an issue caused by the package. 

I also can't replicate this on my live apps or a test app I used this morning for releasing Laravel 10 support.

**Comment by harshadcmr** [comment] 2023-03-11 16:58
@Kyon147  May I know how can I get the store access token  and associated user details with osiset?  if it is possible to get those tokens inside the controllers, then this redirections can be avoided! 

Note : we are saving those token in our side and accessing the admin apis with those token.

**Comment by Kyon147** [comment] 2023-03-12 14:18
@harshadcmr the store access token is grabbed on as part of the authenticate route for the package and automatically saved in the users table.

You can then just use the `api` method that is on the `User` class to call the Shopify API directly or if you want the token just need to grab it from the model directly. `$user->password`

**Comment by rohith016** [comment] 2023-03-13 04:09
@Kyon147 is that token from `$user->password` a user access token or a store access token? if it is user based token can we perform store-based functionalities(like meta field, theme injection.. etc)?

![image](https://user-images.githubusercontent.com/103015707/224606020-08758bb4-f89f-4cb5-8045-b7298dfe2437.png)

this response was got when calling store APIs with that token from `$user->password`

**Comment by Kyon147** [comment] 2023-03-13 09:07
@rohith016 it is the store access token, in the later versions of this package around v12/13 per user auth was removed and is on the roadmap to add back in.

So at the moment you can only auth as the store not the user.

**Comment by harshadcmr** [comment] 2023-03-13 09:21
So how do we get the individual authenticated   associated_user data like 
first_name,email, account_owner ,locale, collaborator etc. ?  @Kyon147

**Comment by Kyon147** [comment] 2023-03-13 09:34
You're unable to with this package at the moment, if you are looking for `Per User Auth` you would need to implement it yourself at the moment https://shopify.dev/docs/apps/auth/oauth/access-modes#online-access

**Comment by Kyon147** [comment] 2023-03-13 09:48
I'm going to close this for now as it does not seem to be a package issue, but feel free to open a discussion if you want to continue the conversation.

**Closed by Kyon147** 2023-03-13 09:48 UTC
