### ISSUE TITLE
Unable to verify Signature due to invalid HMAC

### ISSUE THREAD

**Issue by jasontxf** [Kyon147/laravel-shopify#6] opened 2022-12-07 05:38 UTC
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

App is able to load within iframe when open from the search bar

## Current Behavior

When app load within the iframe, it returns Unable to verify Signature

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Search for your app from the top search bar as shown
![Xnapper-2022-12-07-13 32 14](https://user-images.githubusercontent.com/1124731/206096891-a73323f4-0c32-4684-a1a6-49d005af7a22.png)

2. When the app load it will return the following
![Xnapper-2022-12-07-13 35 21](https://user-images.githubusercontent.com/1124731/206097090-e8b6d6c9-7796-4f98-be3b-992247c19fa1.png)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.3.2
* Laravel Version: v9.41
* PHP Version: v8.1.0

My guess is the "host" parameter was somehow included which invalidates the HMAC.
However, I'm not able to find where exactly the "host" is being inserted as I seem to have removed all I can find throughout the vendor files.

Would appreciate if you could give me some advise on what's possibly causing it and I could look further into it.

Thanks!

**Comment by Kyon147** [comment] 2022-12-08 14:01
Hey @jasontxf the host param is needed, as it is what loads your app into the iframe. 

Signature exception is usually because the the API key is not the one from your app settings or that hmac has failed for some reason.

Are you using blade templates?

**Comment by jasontxf** [comment] 2022-12-08 14:43
Hello @Kyon147 Yes I'm using blade templates.

It's weird that everything would load properly in the iframe when I remove the host param manually.
But when the host param existed, HMAC don't validate. I don't really understand why.

The API key seems valid since I can still load the app in the iframe.

I don't know what information I can provide to assist you. 

Would appreciate it if you could provide me with some advise to troubleshoot.

**Comment by Kyon147** [comment] 2022-12-08 14:49
Ah can you try using the new 17.3.3 that I have just published. It might be an issue with the host param on the blade templates.

**Comment by jasontxf** [comment] 2022-12-09 04:30
I'm sorry if I'm asking a stupid question, may I know how do I switch to this repository from the previous osiset repo when updating in composer?

**Comment by Kyon147** [comment] 2022-12-09 10:42
Hey @jasontxf 

The way I usually do it is using 
````
"repositories": [{
   "type": "vcs",
   "url": "https://github.com/Kyon147/laravel-shopify"
 }],
````
 Then just do `composer update` and this will use my fork and then look for the next version which is `17.3.3`

**Comment by Kyon147** [comment] 2022-12-12 10:50
@jasontxf any luck with the update - let me know if that did not work as it might be something to do with your implementation.

**Comment by jasontxf** [comment] 2022-12-13 03:51
Hello @Kyon147 Thanks for the info on how to update the version. I've just gave it a go and sadly it didn't seems to solve the issue. 

Apart from that, my billing seems to be broken now too. But I'll open a new issue for that. 

If there's a way to privately msg you, I'll be happy to make a video recording of the entire process and send it to you.
As it contains sensitive company data, I'm not able to post a video recording here. 

Please let me know how can I further assist you in this. Thanks!

**Comment by jasontxf** [comment] 2022-12-14 04:45
Hello @Kyon147 , just an updates after spending some time troubleshooting I've found the issue but yet to find the root of the issue.

Basically, at `VerifyShopify.php` `@getRequestData` within the `INPUT` switch source, target parameter included the `host` parameter

![SCR-20221214-hdh](https://user-images.githubusercontent.com/1124731/207506387-44db6f58-78d8-418b-b6ab-b53502acb7b9.png)

Here's a comparison with a working HMAC after removing `host` parameter from the browser.

![SCR-20221214-hiw](https://user-images.githubusercontent.com/1124731/207507056-56c7e109-f12e-4754-942d-5db82f93d097.png)

As you can see, the target included an extra `host` parameter.

Then i look at the url at the browser.

https://....myshopify.com/admin/apps/880b4e975174bc3fd1659c4b1ca7d896/authenticate/token?shop=...&target=%2Fdashboard%3FappLoadId%3D7d293aea-e660-483e-ab87-a6e0c13305fb **_%26host%3DYmxlZWRpbmctcmVsaWMubXlzaG9waWZ5LmNvbS9hZG1pbg_**


I noticed that the & character was escaped with %26, maybe that's why `target` identify it as part of the string and thus failing HMAC verification.

I also noticed that even though I removed the `host` parameter from the browser, during the HMAC verification, host parameter still exists. My guess is Shopify's iFrame included the host parameter as well during the loading of the page.

Which is why when I removed host parameter from the url, everything works as it's properly formatted

So my conclusion is during the redirection from blade, the host parameter probably wasn't parsed properly.

If you could direct me on how the redirection work from external site to embedded app, I might be able to troubleshoot further. 

But this is as far I can go based on my own knowledge. 

I hope that helps!

**Comment by bilfeldt** [comment] 2022-12-15 14:25
@jasontxf I have just tested this on a fresh installation without any problems.

Searching for the app on Shopify and selecting it causes a request with a query like this:

```
/?embedded=1&host=ZXhhbXBsZS5teXNob3BpZnkuY29tL2FkbWlu&shop=example.myshopify.com&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3Mi....
```

and this should be verified like so:

> To verify the request, you need to remove the hmac parameter from the query string and process it through an HMAC-SHA256 hash function
Source: https://shopify.dev/apps/auth/oauth/getting-started

A few questions:

1. Have you tried veryfying the HMAC manually?
2. have you set the environment variables correctly?

You say that your subsequent requests are working just fine?

**Comment by jasontxf** [comment] 2022-12-16 03:24
Hello @Kyon147 

The embedding url is only the beginning of the process I think. After which it will redirect to one of our own blade template which in turn did a redirect to shopify dashboard and open the app in the iframe.

So I suspect is was the blade redirect layer that includes target and host wrongly. But I havent been able to find out which blade did the redirectly exactly as there are a couple of files.

To name a few
- `auth/fullpage_redirect.blade.php`
- `auth/token.blade.php`
- `billing/fullpage_redirect.blade.php`
- `layouts/default.blade.php`


I tried to comment away the redirect part in javascript and somehow it still got redirected to the shopify app and load in the iframe. So I'm not really sure how it's being redirected.

1. Yeah I've traced to the HMAC function and found out that the & character was being escaped somehow thus forming part of the target parameter which invalidates the HMAC.

https://....myshopify.com/admin/apps/880b4e975174bc3fd1659c4b1ca7d896/authenticate/token?shop=...&target=%2Fdashboard%3FappLoadId%3D7d293aea-e660-483e-ab87-a6e0c13305fb **%26host**%3DYmxlZWRpbmctcmVsaWMubXlzaG9waWZ5LmNvbS9hZG1pbg

Instead of `%26` it should have been `"&"` 

So i'm trying to find out which part of the process convert it into %26

2. There's no host parameter in my environment variables. 

Next week I'll give it a go by installing a fresh version of the framework and will let you know when I've identified something new.

Thanks for being patience with me.

**Comment by FamousFirstWords** [comment] 2022-12-16 03:40
I believe the issue is with the ampersand being present when decoding the HMAC. I was able to get around this by overriding the verifyHmac() method in VerifyShopify.php

`
        // We have HMAC, validate it
        $data = $this->getRequestData($request, $hmac['source']);
        foreach ($data as $key => $value) {
            $data[$key] = str_replace('&', '%26', $data[$key]);
        }
`

**Comment by jasontxf** [comment] 2022-12-16 04:44
@FamousFirstWords Thanks for the reply!

Does this mean you have encountered the same issue? It's not just me right?

The ampersand is there because at some point the url have been parsed and special character was being "escaped" and converted into `%26`

**Comment by Kyon147** [comment] 2022-12-16 10:28
I've tested this today and can confirm that `17.3.3` is breaking at install - this is due to some recent PRs I believe, so to make things clean - 17.4.4 reverts those changes so we can go back to a working version and fix the issues in another more controlled way.

**Comment by Kyon147** [comment] 2022-12-16 10:44
I can now confirm that `17.3.4` is working for me as expected. 

Installs fine on blade, app bridge is loading fine and so is billing. 

![Screenshot 2022-12-16 at 10 41 49](https://user-images.githubusercontent.com/32519106/208081254-3fd4f7bd-71c6-4373-a08c-c902ed498e88.png)

Here's the homepage

![Screenshot 2022-12-16 at 10 43 34](https://user-images.githubusercontent.com/32519106/208081492-08402b77-baaf-4c4d-9f2d-bc55e6adc1d0.png)

**Comment by Kyon147** [comment] 2022-12-16 10:45
Closing as it does not seem to be an issue with the package.

**Closed by Kyon147** 2022-12-16 10:44 UTC
Labels: blade-engine, unconfirmed

**Comment by jasontxf** [comment] 2022-12-19 05:36
Hello @Kyon147 Sorry for reopening. 
It's weird that when I run `composer update` it downgrade me to 17.3.2. May I ask how can i Upgrade to 17.3.4? 

Nevertheless, I finally found the **root** of the problem after spending hours to troubleshoot the authentication process!
I also checked v17.3.4 file changes to ensure this portion wasn't included before stating it here..

Here's the root of my issue.

Under `VerifyShopify@tokenRedirect` Line 285,

```php
$filteredQuery = Collection::make($request->query())->except([
    'hmac',
    'locale',
    'new_design_language',
    'timestamp',
    'session',
    'shop',
]);
```

`$filteredQuery` needs to include `'host'` within `except() ` or else `host` will end up being escaped.
Including `host` within it solves all my problems like so!

```php
$filteredQuery = Collection::make($request->query())->except([
    'hmac',
    'locale',
    'new_design_language',
    'timestamp',
    'session',
    'shop',
    'host',
]);
``` 

The url now looks like this after it opened up in shopify dashboard

https://....myshopify.com/admin/apps/880b4e975174bc3fd1659c4b1ca7d896/authenticate/token?shop=....myshopify.com&target=%2Fdashboard%3FappLoadId%3D65b4a585-bfe8-4b56-af37-7ef9e0c29e72

Clean url and it everything works! No more HMAC issue!

This is my root issue. I'm not sure if this makes any sense to the framework. But I hope this will assist you who understands the framework better than I do. Thank you for taking over the maintenance of this framework. Appreciate everything you do!

For now i'm just going to override this function and apply my own fix by overiding the file.

Thanks for all your help!

You may close this if you like :)

**Comment by jasontxf** [comment] 2022-12-19 14:53
Hi @Kyon147 

Yeah I managed to upgrade to `17.3.4`. The issue was still there for me so I'll use my workaround for now.

I'm looking forward to the future updates where I wont need my workaround anymore!

Thanks alot for your help!

**Comment by Kyon147** [comment] 2022-12-19 16:08
Hey @jasontxf 

On a new install, i can not replicate this issue. 

Can you try and outline your steps to reproduce as much as possible? Everything works for me on a fresh install and I don't get the issue you are seeing.

This will help me see if there is a wider issue on the package that I can patch.

**Comment by jasontxf** [comment] 2022-12-27 04:07
Hello @Kyon147 Ok sure! In the coming new year. i'll try it in a new install and provide updates here! 

Thanks for your help!
