### ISSUE TITLE
Laravel Livewire V3 addHeaders Error

### ISSUE THREAD

**Issue by cavitznky** [Kyon147/laravel-shopify#255] opened 2023-12-27 22:52 UTC
Hi everyone,

I want to develop an application with Laravel-livewire v3 but the following code is not working.

When I checked, there is no addHeaders method in v3.

How can I solve this?

inside the ('shopify-app::partials.token_handler') file

```
if (window.Livewire) {
    // livewire
    window.livewire.addHeaders({
        'Authorization': bearer,
        'content-type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest'
    });
}
```

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addHeaders')

@Kyon147

**Comment by Kyon147** [comment] 2023-12-29 14:09
@izsoft I've never used Livewire, so I don't know the answer to this one sadly. 

I'll leave it open and add the help wanted tag, so someone else who also used Livewire might be able to assit.

**Comment by izsoft** [comment] 2023-12-29 16:18
Thank you for your answer @Kyon147, 

I hope there are friends who have solved this problem for **Livewire v3** and I would appreciate if they can help.

By the way, the code I mentioned in the first message works on Livewire v2. So for Livewire v3 it is also necessary to add a token to each request. But I couldn't find how to do it.

**Comment by d-shannon** [comment] 2024-01-13 18:02
Yes, it's possible:

```
        if (Livewire) {
            Livewire.hook('request', ({options}) => {
                options.headers['Authorization'] = `Bearer ${window.sessionToken}`;
                options.headers['Content-Type'] = 'application/json';
                options.headers['X-Requested-With'] = 'XMLHttpRequest';
            });
        }
```

**Comment by cyberkishor** [comment] 2024-01-21 08:35
@d-shannon I have added livewire in our app and added, javascript code in the header but it is still not working. 
https://github.com/Kyon147/laravel-shopify/issues/255#issuecomment-1890634873

The auth user is not showing after the livewire update. 
the session variable is also undefined here <code>${window.sessionToken}</code>


Please suggest me if you have any solution. Thanks in advance.

**Comment by Kyon147** [comment] 2024-01-24 15:48
@cyberkishor This is just a guess as I't not worked with Livewire but check your AppBridge object and see if it still has the right info and that `host` is being passed into it with the stores details.

9 times out of 10 - user being lost between pages or transitions is because of the `host` param being lost so appbridge can reinit.

**Comment by cyberkishor** [comment] 2024-01-24 15:56
@Kyon147 The AppBride is ok and it's past the correct host, the issue is inside the Livewire config or something.

**Comment by Kyon147** [comment] 2024-01-24 15:58
If I have some time this week one evening I'll try and spin up a quick test and see if I can see the issue

**Comment by Kyon147** [comment] 2024-01-30 15:38
Had a look this weekend but not jump out at me yet, so need to do some more digging but will let you know

**Comment by donkooijman** [comment] 2024-02-14 23:35
@izsoft It seems like the middleware setting is no longer in the Livewire 3 configuration file. So the 'verify.shopify' middleware was no longer applied it my case. 

This fixed it for me. I added the following code to AppServiceProvider so the middleware are applied

```
Livewire::setUpdateRoute(function ($handle) {
            return Route::post('/livewire/update', $handle)
                ->middleware(['verify.shopify']);
        });
```

**Comment by izsoft** [comment] 2024-02-19 16:30
Greetings,

Thank you for your support.

As @d-shannon  said, the token_handler blade file needs to be updated.

Also as @donkooijman  said or as I mentioned below, you need to specify the middleware in the service providers.

`Livewire::addPersistentMiddleware(VerifyShopify::class);`

@Kyon147

**Comment by d-shannon** [comment] 2024-03-12 11:16
Yes confirming @izsoft comment. I updated the token_handler and applied the persistent middleware.

**Comment by Kyon147** [comment] 2024-03-12 11:36
Great work all, can someone create a PR for this? It will allow others to use Limewire v3 if they wish or we can add the steps into the wiki.

**Comment by MarkusPayne** [comment] 2024-03-21 20:08
I created a PR with based on @d-shannon comment with an updated token_handler blade file

**Comment by Kyon147** [comment] 2024-03-25 11:02
#286

**Comment by FrankWiebe** [comment] 2024-03-27 16:38
I'm having trouble getting livewire to work. I've added this to the app service provider
```
Livewire::setUpdateRoute(function ($handle) {
    return Route::post('/livewire/update', $handle)
          ->middleware(['verify.shopify']);
});

Livewire::addPersistentMiddleware(VerifyShopify::class);
```
I've also added the changes in your PR. But livewire isn't making any round trips to the server. I can confirm the livewire styles and script is being loaded. But even AlpineJS isn't working.
Any ideas?

**Comment by Kyon147** [comment] 2024-07-08 09:27
Closing this issue as it is getting too long with other issues. Please open new issues if needed.

**Closed by Kyon147** 2024-07-08 09:27 UTC
Labels: help wanted, question
