### ISSUE TITLE
App Dashboard did not load on Shopify store.

### ISSUE THREAD

**Issue by auspicious-soft** [Kyon147/laravel-shopify#107] opened 2023-03-07 04:51 UTC
I am using the osiset 17.1 package on Laravel 7.1. App installed successfully and working file. Next day when we open app dashboard did not open.
![Screenshot_2](https://user-images.githubusercontent.com/60027228/223323610-5b13368a-4895-4d40-b1dd-5e674c010df5.png)
 When I uninstall the app and install again it working fine. Its works for same day. Next day same issue occur again.

**Comment by Kyon147** [comment] 2023-03-07 12:11
@auspicious-soft upgrade to the latest version and try again, we are on `17.4.4`

**Comment by auspicious-soft** [comment] 2023-03-07 12:31
No. When I moved to other url in shopify admin and come back to app its not loaded.

**Comment by Kyon147** [comment] 2023-03-07 13:23
Have you upgraded and tried again?

**Comment by auspicious-soft** [comment] 2023-03-09 05:34
Token is missing when redirect to another root and app home page not load.

I have also added the host parameter in token function in Auth traits but it did not work. I am facing this issue in all apps.
![Screenshot_3](https://user-images.githubusercontent.com/60027228/223929559-b54a7382-b314-4d7e-9d87-10f6a58489c9.png)

**Comment by Kyon147** [comment] 2023-03-09 10:39
@auspicious-soft I can't help you unless you respond to my questions, have you upgraded to the latest version of the package which is `17.4.4`?

I cannot replicate this issue on a fresh install, so something is happening on your end - can you try and upgrade the package and try again as if you are on 17.1 there has been a lot of fixes introduced.

**Comment by pkarczmarczyk94** [comment] 2023-03-09 15:48
I have the same issue. I've upgraded to version 17.4.4. Sometimes the app dashboard is shown but sometimes it's a blank page
![image](https://user-images.githubusercontent.com/15942667/224077388-3424e5fd-f049-4a5e-ad7e-a32456a10f35.png)
Additionally, every second save of a form on the dashboard ends with 500
![image](https://user-images.githubusercontent.com/15942667/224077612-66c0bd3f-2ae2-4d73-8853-e03913f1aab8.png)

**Comment by Kyon147** [comment] 2023-03-09 15:56
@pkarczmarczyk94 are you using the blade template? it sounds like the JWT token could be expiring maybe

**Comment by pkarczmarczyk94** [comment] 2023-03-09 15:57
Yes it's blade template

**Comment by Kyon147** [comment] 2023-03-09 15:59
When you have the blank page, do you see any errors in the logs or the console in the browser?

**Comment by pkarczmarczyk94** [comment] 2023-03-09 16:05
After reinstalling the problem do not occur. Unfortunatelly we have the problem on production app so I would like to avoid telling the client "please uninstall and install again".
What I was able to seee previously (no screens unfortunatelly) there was "embedded" request canceled, then the next embedded request returned 302. Now I can see 
![image](https://user-images.githubusercontent.com/15942667/224082371-ae0175df-b0c4-4ab9-acca-c9019028ceb3.png)
but I cannot recall if that was the same endpoint

**Comment by pkarczmarczyk94** [comment] 2023-03-09 16:18
After installing app on local env i end up in infinite loop 
![image](https://user-images.githubusercontent.com/15942667/224085835-4b5644eb-c5f4-4eaf-aa64-6bb3be1c2944.png)
![image](https://user-images.githubusercontent.com/15942667/224085749-5ec53bc2-f713-4421-ae19-5c7006ca086c.png)
![image](https://user-images.githubusercontent.com/15942667/224085875-f36e5ac3-9090-4cb1-a1e3-56a73c9814ae.png)
Will try to debug something. May be it's caused by app-bridge returning 302

**Comment by pkarczmarczyk94** [comment] 2023-03-09 16:28
![image](https://user-images.githubusercontent.com/15942667/224088355-ed7d26cf-77cb-40b9-ae4a-2320dac449ba.png)
Heres a dump of token request payload
![image](https://user-images.githubusercontent.com/15942667/224088250-a940d927-8d6f-43f4-977e-108af3237eb9.png)

**Comment by pkarczmarczyk94** [comment] 2023-03-09 17:17
Ok so the redirect is caused because of expired token (I guess)
![image](https://user-images.githubusercontent.com/15942667/224103191-6c9e1121-ac20-433f-a7c8-2ed58cd4653f.png)
Assertion for expiration date fails 
![image](https://user-images.githubusercontent.com/15942667/224103449-13079c50-5277-4ace-b43f-020d0a2a9b18.png)
![image](https://user-images.githubusercontent.com/15942667/224104278-41b76145-c386-4d28-ad3c-2d1f78797c4d.png)

**Comment by pkarczmarczyk94** [comment] 2023-03-09 17:38
Ok, so it turned out that my docker container desynced on time... That's why I was not able to get the token working...
I'm still left with the expiring token on the form. Do you have some ideas how we could fix that?

**Comment by pkarczmarczyk94** [comment] 2023-03-09 19:57
Ok I was able to make it working. I used tokenRedirect and it helped. Would be great to add information somewhere in (https://github.com/Kyon147/laravel-shopify/wiki/Authentication-Process) that you need to also pass host down the road

**Comment by Kyon147** [comment] 2023-03-09 21:33
@pkarczmarczyk94 glad you got it working. It is on the wiki but it might be better in the auth process as you mention.

**Comment by Kyon147** [comment] 2023-03-10 08:45
I've added the updated bit about the host param into the auth flow wiki

**Comment by Kyon147** [comment] 2023-03-11 09:14
This issue seems to be fixed for @pkarczmarczyk94 so going to close this ticket now but @auspicious-soft if you run into issues again, please re-open.

**Closed by Kyon147** 2023-03-11 09:14 UTC
Labels: bug, unconfirmed

**Comment by faridmovsumov** [comment] 2023-10-01 18:49
I have a fresh installation (19.1) and am facing the same issue. I have an infinite loop. 
I am using Laravel sail. And running https with express.dev
Not sure what is wrong in my setup.

<img width="1728" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/1541412/324c9ca4-351b-48dc-8a2d-4471d0d87905">
